#pragma once
#include <Term/Helper.h>
#include <Term/Nodes.h>
#include <Term/PiNode.h>
#include <Term/RefNode.h>
#include <Term/TermNode.h>
#include <Term/UnivNode.h>
#include "Value/Context.h"
#include <Term/TermVisitor.h>